### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by walkingpendulum** [ee0703/console_video#3]
Hello, guys, I've tried to run your script and thats what I've got:

MacBook-Pro:console_video oay$ python player.py test.mp4 
Traceback (most recent call last):
  File "player.py", line 68, in <module>
    play(sys.argv[1])
  File "player.py", line 20, in play
    iv.open(file_path)
  File "/Users/OgeL/console_video/pipeffmpeg.py", line 431, in open
    stderr=sp.PIPE,
  File "/anaconda/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

What I am doing wrong?

**Comment by ee0703** [comment]
the script is based on ffmpeg, you should have  ffmpeg installed first

```
➜  ~  which ffmpeg
/usr/local/bin/ffmpeg
```
